import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "aikeruiclean.com",
      },
    ],
  },

  // Security headers applied to all routes
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://*.googletagmanager.com https://www.google-analytics.com https://*.google-analytics.com",
              "style-src 'self' 'unsafe-inline'",
              "img-src 'self' data: blob: https://www.aikeruiclean.com https://aikeruiclean.com https://www.googletagmanager.com https://img.youtube.com",
              "font-src 'self'",
              "connect-src 'self' https://api.brevo.com https://*.stripe.com https://*.google-analytics.com https://*.analytics.google.com https://www.googletagmanager.com",
              "frame-src 'self' https://*.stripe.com https://www.googletagmanager.com",
              "object-src 'none'",
              "base-uri 'self'",
              "form-action 'self'",
            ].join("; "),
          },
        ],
      },
    ];
  },


async redirects() {
  return [
    { source: "/products/62276226", destination: "/products/weizhuo-auto-scrubber-x3b-3d-floor-rotary-brush-and-pad-drive", permanent: true },
    { source: "/products/62675375", destination: "/products/ice-ride-scrubber-dryer-rs32-floor-rotary-brush", permanent: true },
    { source: "/products/63279046", destination: "/products/floor-scrubber-spare-parts-center-lock-pad-retainer", permanent: true },
    { source: "/products/65654189", destination: "/products/dulevo-5000-sweeper-spare-parts-main-brush-roller-brush-steel-wire-mixed-pp-ppl", permanent: true },
    { source: "/products/65661363", destination: "/products/hako-citymaster-600-steel-wire-mixed-pp-gutter-sweeper-brush", permanent: true },
    { source: "/products/65669315", destination: "/products/nilfisk-viper-gaomei-single-disc-machine-spare-part-carpet-shampoo-brush", permanent: true },
    { source: "/products/65673327", destination: "/products/snow-sweeping-disc-wafer-brush-pp-ring-mixed-ring-steel-wire-ring", permanent: true },
    { source: "/products/65749296", destination: "/products/city-sweeper-custom-pp-mixed-steel-wire-4-rows-sweeper-side-brush", permanent: true },
    { source: "/products/66284266", destination: "/products/kacher-bd50-50c-floor-scrubber-brush-pp-red-disc-brush", permanent: true },
    { source: "/products/66373427", destination: "/products/weizhuo-cwz-x2d-auoto-scrubber-parts-disc-brush", permanent: true },
    { source: "/products/66564829", destination: "/products/soft-carpet-shampoo-brush-with-shower-feed-holes", permanent: true },
    { source: "/products/66571551", destination: "/products/comac-l20-b-e-scrubber-dryer-spare-part-floor-cleaning-rotary-brush-19inch", permanent: true },
    { source: "/products/66804443", destination: "/products/aditek-amber-66-baby-43-coral-65-jade-66-opal-66-quartz-66-sapphire-65-floor-scr", permanent: true },
    { source: "/products/83726161", destination: "/products/22-inch-ppl-floor-rotary-brush-for-comac-fimap-auto-scrubber-machine", permanent: true },
    { source: "/products/83869572", destination: "/products/kelenco-floor-cleaning-machine-parts-accessories-16inch-scrubber-disc-brush", permanent: true },
    { source: "/products/84314300", destination: "/products/bennett-hussar-660b-auto-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/87026133", destination: "/products/dulevo-fuan-200-cleaning-equipment-part-steel-wire-sweeper-side-brush", permanent: true },
    { source: "/products/87141258", destination: "/products/dulevo-6000-sweeper-gutter-broom-5050041877", permanent: true },
    { source: "/products/101720530", destination: "/products/dulevo5000-sweeper-800mm-front-brush", permanent: true },
    { source: "/products/101905818", destination: "/products/ipc-cleantime-100-bt-85-cleantime-160-bt-85-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/102631231", destination: "/products/16inch-comac-85b-electric-scrubber-machine-spare-part-disc-brush-pad-driver", permanent: true },
    { source: "/products/134966441", destination: "/products/pad-driver-for-auto-scrubber-machine-single-disc-machine", permanent: true },
    { source: "/products/162621838", destination: "/products/17-inch-fiorentini-80-m-smile-85-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/266257736", destination: "/products/floor-scrubber-machine-spare-part-16-inch-pad-driver-for-nilfisk-pad-holder", permanent: true },
    { source: "/products/103859748515", destination: "/products/china-factory-floor-scrubber-spare-part-disc-brush-for-kacher-bd530", permanent: true },
    { source: "/products/103099374883", destination: "/products/good-quality-clutch-plate-for-scrubbing-machine-accessories", permanent: true },
    { source: "/products/11477313796", destination: "/products/pad-holder-17-inch-advance-56380378-3-lug", permanent: true },
    { source: "/products/103775024782", destination: "/products/floor-scrubber-spare-part-drain-hose-assembly-scrubber-hose-set", permanent: true },
    { source: "/products/103699350051", destination: "/products/clutch-plate-center-locator-for-scrubbing-brush-pad-retainer-retainer-centering", permanent: true },
    { source: "/products/102503483951", destination: "/products/kacher-oem-drain-hose-id38-1100mm-for-kacher-b40-b60", permanent: true },
    { source: "/products/103655156338", destination: "/products/forklift-road-sweeper-attachment-brushes-forklift-brush-replacement-strip-brush", permanent: true },
    { source: "/products/103860143191", destination: "/products/viper-20inch-floor-scrubbing-brush-for-as510b-as5160-auto-scrubbers", permanent: true },
    { source: "/products/101548652397", destination: "/products/cleaning-equipment-floor-scrubber-machine-parts-clutch-plate-np-9200", permanent: true },
    { source: "/products/11701766457", destination: "/products/cleaning-equipment-floor-scrubber-machine-parts-disc-brush-for-kacher-bd530-bd90", permanent: true },
    { source: "/products/103862201645", destination: "/products/pp-430mm-floor-scrubber-cleaning-machine-brush-for-tennant-t2-t3", permanent: true },
    { source: "/products/103854277933", destination: "/products/part-399242-1220214-t5-grit-abrasive-stripping-brushes-fits-tennant", permanent: true },
    { source: "/products/103851699691", destination: "/products/china-factory-directly-sale-carpet-scrubbing-brush-for-any-brand", permanent: true },
    { source: "/products/104430594920", destination: "/products/floor-scrubber-universal-solenoid-valve-water-solenoid-valve-fits-tennat-nilfik", permanent: true },
    { source: "/products/102722220914", destination: "/products/auto-scrubber-parts-rubber-strip-squeegee-for-tennant-t16", permanent: true },
    { source: "/products/102013107468", destination: "/products/nilfisk-viper-fang-18c-floor-scrubber-disc-brush-vf80211b", permanent: true },
    { source: "/products/104387336096", destination: "/products/carbon-brush-for-floor-scrubber-machine", permanent: true },
    { source: "/products/102498811796", destination: "/products/drain-hose-tennant-t3-t5-1043538-for-floor-scrubber", permanent: true },
    { source: "/products/103138399643", destination: "/products/349mm-roller-brush-replacement-nylon-brush-kits-for-cleaning-equipment-apply-to", permanent: true },
    { source: "/products/103113429415", destination: "/products/pad-holder-driver-accessories-for-sweeper-machine-for-viper", permanent: true },
    { source: "/products/101539693092", destination: "/products/floor-cleaning-equipment-spare-part-kacher-np-700-clutch-plate", permanent: true },
    { source: "/products/103131390763", destination: "/products/45-inch-cylindrical-scrub-brush-pp-abrasive-roller-brush-high-quality", permanent: true },
    { source: "/products/102500143157", destination: "/products/floor-scrubber-spare-part-drain-hose-for-tennant-t300-t500", permanent: true },
    { source: "/products/103324466186", destination: "/products/china-cleaning-parts-factory-lug-fixing-for-scrub-brush", permanent: true },
    { source: "/products/102005253936", destination: "/products/nilfisk-viper-as4325-as4335-17-inch-floor-scrubber-disc-brush-vs15374", permanent: true },
    { source: "/products/101440719895", destination: "/products/scrubber-spare-part-squeegee-assembly-suitable-for-various-scrubber-models", permanent: true },
    { source: "/products/103916792396", destination: "/products/diamond-products-17inch-floor-scrubbing-brush", permanent: true },
    { source: "/products/103569939119", destination: "/products/nilfisk-l08812891-floor-scrubber-disc-disk-brush-suitable-for-nilfisk", permanent: true },
    { source: "/products/103320457980", destination: "/products/single-disc-machine-t290-t300-t300e-clutch-plate-clutch-disc-clutch-cover-for-sc", permanent: true },
    { source: "/products/103655310946", destination: "/products/floor-machine-spare-parts-for-different-brands-squeegee-assembly-floor-scrubber", permanent: true },
    { source: "/products/103854650360", destination: "/products/tennant-605123-pad-driver-assembly", permanent: true },
    { source: "/products/12344458268", destination: "/products/kacher-bds-43-150-c-bds-43-duo-c-bds-43-410-c-floor-scrubber-dryer-spare-parts-f", permanent: true },
    { source: "/products/103820116731", destination: "/products/produce-any-brand-floor-scrubber-machine-brushes-accessories-polishing-rotary-fl", permanent: true },
    { source: "/products/104155251862", destination: "/products/cleaning-equipment-parts-tennat-spare-part-brush-pad-holder-motor-filter-drain-h", permanent: true },
    { source: "/products/101521510723", destination: "/products/dulevo-5000-sweeper-spare-parts-main-brush-roller-brush-ppl", permanent: true },
    { source: "/products/103210457648", destination: "/products/gutter-broom-road-snow-sweeper-poly-circular-brush-sweeper-side-brush", permanent: true },
    { source: "/products/103321052061", destination: "/products/clutch-plate-for-scrubbers-machine-disc-brush", permanent: true },
    { source: "/products/11675059376", destination: "/products/kacher-bd40-12c-pp-red-disc-brush", permanent: true },
    { source: "/products/103636270746", destination: "/products/floor-machine-spare-parts-for-scrubber-dryer-tanjie-squeegee-assembly-floor-scru", permanent: true },
    { source: "/products/103743012354", destination: "/products/industrial-round-floor-cleaning-disc-brush-used-for-washing-floor-machine", permanent: true },
    { source: "/products/104646272798", destination: "/products/floor-scrubber-karch-bd50-50-squeegee-rubber-natural-rubber-polyurethane-materia", permanent: true },
    { source: "/products/103612505105", destination: "/products/16inch-taski-floor-scrubber-disc-brush-with-pp-material-scrubbing-brush-floor-bu", permanent: true },
    { source: "/products/103555457882", destination: "/products/factory-directly-sale-comac-fimap-cleaning-floor-scrubber-brush", permanent: true },
    { source: "/products/11920183886", destination: "/products/hako-b45-scrubber-machine-spare-part-disc-brush-pad-holder", permanent: true },
    { source: "/products/103857638931", destination: "/products/tennant-nobles-1016810-nylon-3-lug-brush-20-for-t300e-speed-scrub-300", permanent: true },
    { source: "/products/102029927808", destination: "/products/viper-ls160-ls160hd-17-inch-pa-floor-scrubber-disc-brush-for-cleaning-machine", permanent: true },
    { source: "/products/103154334942", destination: "/products/the-sense-of-goods-is-easy-to-use-numatic-cleaning-equipment-parts-sweeper-floor", permanent: true },
    { source: "/products/102282413983", destination: "/products/17-scrub-pad-driver-for-viper-as4325-as4335-floor-scrubber-part-vs15440", permanent: true },
    { source: "/products/103144666457", destination: "/products/cleaning-equipment-parts-13inch-floor-scrubber-disc-brush-suitable-for-nilfisk-s", permanent: true },
    { source: "/products/104629863014", destination: "/products/tennant-t7-drive-wheel-floor-scrubber-machine-amer-drive-wheel-motor", permanent: true },
    { source: "/products/102494191141", destination: "/products/np9200-clutch-plate-universal-pad-driver-clutch-plate-for-most-standard-machines", permanent: true },
    { source: "/products/103895966886", destination: "/products/floor-scrubber-spare-part-pad-driver-with-np-9200-clutch-plate-for-singe-disc-ma", permanent: true },
    { source: "/products/104152244725", destination: "/products/vacuum-motor-tennant-vacuum-motor-for-floor-scrubber-machine", permanent: true },
    { source: "/products/103008793434", destination: "/products/floor-scrubber-spare-part-vacuum-hose-and-drain-hose-for-tenant-t500-t500e-and-n", permanent: true },
    { source: "/products/104940123244", destination: "/products/nilfisk-viper-gaomei-single-disc-machine-spare-part-carpet-shampoo-brush", permanent: true },
    { source: "/products/101535080815", destination: "/products/floor-cleaning-equipment-spare-part-magnet-buckle-clutch-plate", permanent: true },
    { source: "/products/104161545443", destination: "/products/tennant-t5-electromagnetic-valve-solenoid-valve", permanent: true },
    { source: "/products/12343596523", destination: "/products/hawk-floor-machine-19-pad-driver-with-np9200", permanent: true },
    { source: "/products/102484930197", destination: "/products/factory-sale-kacher-bd50-50-19inch-floor-scrubber-disc-brush-for-floor-scrubber", permanent: true },
    { source: "/products/101539965819", destination: "/products/gaomei-1900-hako-e800-floor-sweeper-roller-sweeper-brush", permanent: true },
    { source: "/products/11672380833", destination: "/products/comac-86b-floor-scrubber-parts-squeegee", permanent: true },
    { source: "/products/103774487871", destination: "/products/clutch-plate-with-brush-holder-tufted-pad-disc-driver-floor-buffer-pad-holder-fo", permanent: true },
    { source: "/products/104941081863", destination: "/products/nilfisk-viper-gaomei-single-disc-machine-spare-part-carpet-shampoo-brush", permanent: true },
    { source: "/products/104940987673", destination: "/products/nilfisk-viper-gaomei-electric-spin-scrubber-power-brush-floor-scrubber-cleaning", permanent: true },
    { source: "/products/103105081014", destination: "/products/first-quality-brushstrip-disc-brush-for-weizhuo-auto-scrubber-x9-105-scrubber-bu", permanent: true },
    { source: "/products/104786452939", destination: "/products/minuteman-port-a-scrub-12-spare-part-roller-brush-sweeper-brush", permanent: true },
    { source: "/products/11701761732", destination: "/products/gaomei-floor-scrubber-gm50b-spare-part-disc-brush-pad-driver", permanent: true },
    { source: "/products/102511577886", destination: "/products/factory-sale-ipc-ct40-18inch-floor-scrubber-disc-brush-for-floor-scrubber", permanent: true },
    { source: "/products/104425081122", destination: "/products/tenant-floor-scrubber-machine-brush-with-pp-bristles-polypropylene-brush", permanent: true },
    { source: "/products/103206399694", destination: "/products/the-newest-road-sweeper-parts-brushes-broom-side-brush-for-electric-road-sweeper", permanent: true },
    { source: "/products/104445213799", destination: "/products/floor-scrubber-machine-parts-tennnt-1014274-drain-hose-fits-t7-scrubber", permanent: true },
    { source: "/products/102858791034", destination: "/products/floor-scrubber-spare-parts-disc-brush-for-kacher-bds-43-floor-scrubber-brush", permanent: true },
    { source: "/products/104353808532", destination: "/products/squeegee-rubber-set-fits-tennant-500mm-1011456-1011232-t3-t3e-t5-t5e", permanent: true },
    { source: "/products/104340418624", destination: "/products/china-factory-wholesale-single-disc-machine-rotary-brush-single-disc-brush", permanent: true },
    { source: "/products/104790988611", destination: "/products/pad-holder-with-3-lugs-np-9200-for-floor-cleaning-machine-13-inch-box-cleaning-b", permanent: true },
    { source: "/products/101539483146", destination: "/products/floor-cleaning-equipment-spare-part-scrubber-black-clutch-plate-for-175-flange", permanent: true },
    { source: "/products/106458238195", destination: "/products/nilfisk-9099999000-pp-disk-brush-370mm-14inch-for-nilfisk-sc351", permanent: true },
    { source: "/products/101559442162", destination: "/products/cleaning-equipment-part-pp-tenant-t17-16inch-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/101535303149", destination: "/products/floor-cleaning-equipment-spare-part-tenant-clutch-plate", permanent: true },
    { source: "/products/104461908694", destination: "/products/karche-kit-squeege-suction-rubber-standard-for-scrubber-machine", permanent: true },
    { source: "/products/103126300274", destination: "/products/floor-buffer-brush-stripping-brush-for-carpet-cleaning-monobrush", permanent: true },
    { source: "/products/104453924843", destination: "/products/pp-steel-mixed-street-road-sweeper-wafer-disc-brush-for-bobcat", permanent: true },
    { source: "/products/103221357071", destination: "/products/high-quality-rotary-brush-and-good-quantity-assured-main-broom-for-sweeper-equip", permanent: true },
    { source: "/products/103717136309", destination: "/products/factory-directly-sale-scrubber-cleaning-machine-part-squeegee-assembly", permanent: true },
    { source: "/products/11476190455", destination: "/products/short-trim-pad-driver-13-inch-advance-30758a", permanent: true },
    { source: "/products/103851462823", destination: "/products/china-factory-directly-sale-floor-scrubber-machine-brush-for-any-brand", permanent: true },
    { source: "/products/101521634780", destination: "/products/kacher-city-sweeper-spare-parts-53inch-pp-mixed-steel-wire-ppl-cylindrical-brush", permanent: true },
    { source: "/products/104074500810", destination: "/products/36v-3-stg-vacuum-motor-tennant-vacuum-motor", permanent: true },
    { source: "/products/104941417043", destination: "/products/nilfisk-viper-gaomei-carpet-shampoo-brush-high-quality-brush-for-floor-scrubber", permanent: true },
    { source: "/products/11717037938", destination: "/products/gaomei-floor-scrubber-machine-gm230-gm160-spare-part-roatary-disc-brush", permanent: true },
    { source: "/products/102012843348", destination: "/products/nilfisk-viper-ls160-ls160hd-16-inch-pad-driver-holder-for-floor-scrubber-vf75421", permanent: true },
    { source: "/products/104482453716", destination: "/products/floor-scrubber-machine-parts-numatic-brush-buckle-center-lock-clutch-plate", permanent: true },
    { source: "/products/104353914601", destination: "/products/drain-hose-assembly-tennant-for-floor-scrubber-machine", permanent: true },
    { source: "/products/103322772606", destination: "/products/t7amr-t16amr-t16-competitive-price-clutch-plate-scrubber-spare-parts", permanent: true },
    { source: "/products/101794807564", destination: "/products/i-mop-xl-floor-scrubber-brush-disc-brush", permanent: true },
    { source: "/products/11701884110", destination: "/products/gaomei-auto-floor-scrubber-gm70bt-gm110bt70-disc-rotary-brush-pad-holder", permanent: true },
    { source: "/products/103215452184", destination: "/products/road-sweeper-nylon-brush-main-roller-brush-cylindrical-scrub-brush", permanent: true },
    { source: "/products/102451676435", destination: "/products/tennant-t300e-floor-scrubber-disc-brush-factory-sales-for-floor-scrubber", permanent: true },
    { source: "/products/101570361535", destination: "/products/cleaning-equipment-part-customized-tynex-abrasive-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/103347384167", destination: "/products/wholesale-a-variety-of-styles-to-suit-a-variety-scrubbers-clutch-disc-clutch-pla", permanent: true },
    { source: "/products/103860452005", destination: "/products/for-tennant-karche-hako-floor-scrubber-machine-rotary-stripping-brush-black-clea", permanent: true },
    { source: "/products/104567660740", destination: "/products/commercial-anti-slip-custom-printed-welcome-logo-door-mat-outdoor-floor-hotel-en", permanent: true },
    { source: "/products/11096774455", destination: "/products/auto-floor-scrubber-cleaning-equipment-parts-clutch-plate", permanent: true },
    { source: "/products/102272210001", destination: "/products/14-inch-disc-brush-for-viper-as380", permanent: true },
    { source: "/products/103775291549", destination: "/products/recovery-tank-drain-hose-assembly-suction-hose-drain-hose", permanent: true },
    { source: "/products/103853667740", destination: "/products/china-factory-directly-sale-long-lasting-taski-swingo-xp-r-bms", permanent: true },
    { source: "/products/12343562955", destination: "/products/hawk-floor-cleaning-equipment-spare-part-16-tufted-pad-driver-with-riser-and-np9", permanent: true },
    { source: "/products/102013200216", destination: "/products/nilfisk-viper-fang-18c-430mm-pad-driver-holder-for-floor-scrubber-vf80212a", permanent: true },
    { source: "/products/12062630493", destination: "/products/kacher-bd530-floor-scrubber-spare-parts-sweeper-disc-brush-pad-driver", permanent: true },
    { source: "/products/1000141211365", destination: "/products/nilfisk-advance-lavor-cleaning-equipment-part-13-inch-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/104124642370", destination: "/products/suitable-for-tennant-1062393-water-solenoid-valve-water-solution-valve", permanent: true },
    { source: "/products/11756940369", destination: "/products/weizhuo-auto-scrubber-machine-x7-85-spare-part-floor-disc-brush-and-pad-driver", permanent: true },
    { source: "/products/104156945621", destination: "/products/cleaning-equipment-parts-water-filter-for-floor-scrubber-machine", permanent: true },
    { source: "/products/104386642322", destination: "/products/oem-replacement-parts-aftermarket-nilfisk-disc-brush", permanent: true },
    { source: "/products/105580309184", destination: "/products/floor-scrubber-machine-amer-drive-wheel-motor-wheel-traction-wheel", permanent: true },
    { source: "/products/12146263221", destination: "/products/cleaning-machine-spare-part-kacher-b140-ppl-17-5-inch-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/104941162657", destination: "/products/floor-rotating-cleaning-tile-scrubber-brush-single-disc-machine-spare-part-carpe", permanent: true },
    { source: "/products/101939920202", destination: "/products/factory-sales-squeegee-blade-for-floor-scrubber-with-nr-pu-material", permanent: true },
    { source: "/products/11697883237", destination: "/products/dulevo-5000-sweeper-spare-part-steel-wire-mixed-pp-side-brush", permanent: true },
    { source: "/products/101558246394", destination: "/products/floor-scrubber-main-brush-cleaning-equipment-parts-roller-brush-for-tennant-t12", permanent: true },
    { source: "/products/103211539526", destination: "/products/main-hard-roller-brush-polypropylene-cylindrical-sweep-roller-brush", permanent: true },
    { source: "/products/104567989135", destination: "/products/good-quality-bathroom-anti-slip-mat-shower-anti-fall-rubber-outdoor-drainage-and", permanent: true },
    { source: "/products/101942138567", destination: "/products/factory-sales-floor-scrubber-squeegee-with-nr-pu-material", permanent: true },
    { source: "/products/103126271154", destination: "/products/scrubmaster-rotary-brush-i-mop-monobrush-cleaning-brush-kit-nylon-brush", permanent: true },
    { source: "/products/101562835129", destination: "/products/hot-sale-floor-scrubber-disk-brush-for-taski", permanent: true },
    { source: "/products/102033468084", destination: "/products/17-inch-pp-floor-scrubber-disc-brush-for-viper-fang-18c", permanent: true },
    { source: "/products/101560194300", destination: "/products/cleaning-equipment-floor-scrubber-machine-parts-ppl-disc-brush-for-tennant-t7", permanent: true },
    { source: "/products/103859939671", destination: "/products/high-quality-single-disc-machine-spare-part-pad-driver-for-viper-ls160", permanent: true },
    { source: "/products/103635968707", destination: "/products/universal-washing-machine-spare-part-accessory-pe-1m-2m-flexible-wash-machine-di", permanent: true },
    { source: "/products/103707738977", destination: "/products/factory-direct-sales-floor-scrubber-spare-part-squeegee-assembly-suitable-tennan", permanent: true },
    { source: "/products/102005918795", destination: "/products/nilfisk-viper-as530r-20-inch-floor-scrubber-disc-brush-vr25014", permanent: true },
    { source: "/products/103008396284", destination: "/products/factory-direct-sales-20inch-floor-scrubber-disc-brush-for-tenant-t300-t300e-1213", permanent: true },
    { source: "/products/104649744346", destination: "/products/5pcs-floor-pads-for-scrubbing-polishing-stripping-and-burnishing-380mm", permanent: true },
    { source: "/products/103126423386", destination: "/products/cleaning-rotary-floor-scrubber-brush-style-high-plate-marble-high-cost-performan", permanent: true },
    { source: "/products/102012819567", destination: "/products/nilfisk-viper-ls160-ls160hd-17-inch-floor-scrubber-disc-brush-vf75434", permanent: true },
    { source: "/products/104461924750", destination: "/products/floor-scrubber-machine-brush-disc-rotary-brush-with-different-size-brand-color-m", permanent: true },
    { source: "/products/103115116776", destination: "/products/vr25014-20-inch-floor-scrubber-disc-brush-suitable-for-nilfisk-viper-as530r-on-s", permanent: true },
    { source: "/products/104671308906", destination: "/products/17-inch-round-nylon-pp-floor-polishing-disc-brush-for-floor-scrubber-from-china", permanent: true },
    { source: "/products/104159916560", destination: "/products/tennant-103782-dust-panel-filter-vacuum-filter-for-t7-5680-5700-floor-scrubbers", permanent: true },
    { source: "/products/104567194832", destination: "/products/pvc-tube-removable-diy-splice-foldable-drainage-anti-slip-swimming-pool-mat-roll", permanent: true },
    { source: "/products/104674362747", destination: "/products/17-inch-floor-cleaning-machine-accessories-auto-scrubber-disc-brushes", permanent: true },
    { source: "/products/102500220088", destination: "/products/scrubber-black-semi-drawn-drain-hose-for-tennant-t3e", permanent: true },
    { source: "/products/102498993381", destination: "/products/vacuum-hose-tennant-t3-t5-and-t7-1014026-for-floor-scrubber", permanent: true },
    { source: "/products/104426608814", destination: "/products/floor-scrubber-machine-16inch-sponge-pad-of-pad-driver-pad-holder-tennant-nilfis", permanent: true },
    { source: "/products/104386960504", destination: "/products/carbon-brush-for-floor-scrubber-machine", permanent: true },
    { source: "/products/102004908611", destination: "/products/nilfisk-viper-as380-15-15-inch-floor-scrubber-disc-brush-vf89801", permanent: true },
    { source: "/products/104156930512", destination: "/products/long-service-life-tennant-contactor-complete", permanent: true },
    { source: "/products/102033283942", destination: "/products/viper-fang-18c-17-inch-pa-floor-scrubber-disc-brush-for-cleaning-machine", permanent: true },
    { source: "/products/103142297056", destination: "/products/cleaning-equipment-spare-parts-floor-scrubber-sweeper-disc-brush-pad-driver-for", permanent: true },
    { source: "/products/103859641084", destination: "/products/taski-carpet-shampoo-brush-17inch-disc-floor-polisher", permanent: true },
    { source: "/products/103851372125", destination: "/products/floor-scrubber-spare-part-disk-brush-for-taski-swingo-450-455-750-755", permanent: true },
    { source: "/products/103636604023", destination: "/products/floor-scrubber-spare-blades-part-squeegee-water-absorbing-scraper-squeegee-blade", permanent: true },
    { source: "/products/103215915956", destination: "/products/sweeper-cylindrical-brush-roller-sweeper-main-broom", permanent: true },
    { source: "/products/102012878476", destination: "/products/20-inch-floor-scrubber-pad-driver-for-viper-as530r", permanent: true },
    { source: "/products/103210702163", destination: "/products/high-quality-marble-stainless-steel-wire-boat-hull-underwater-floor-cleaning-bru", permanent: true },
    { source: "/products/103187042561", destination: "/products/the-manufacturer-recommended-big-sales-brush-steel-wire-gutter-broom-side-brushe", permanent: true },
    { source: "/products/104385891129", destination: "/products/tennat-1213803-water-solenoid-valve-24-volt-water-solenoid-valve-fits-tennnt-t2", permanent: true },
    { source: "/products/104941102056", destination: "/products/floor-scrubber-machine-spare-part-16-inch-pad-driver-machine-brush", permanent: true },
    { source: "/products/103386464427", destination: "/products/tenant-s20-s30-asphalt-road-cement-floor-push-dust-cleaner-industrial-floor-swee", permanent: true },
    { source: "/products/103391604264", destination: "/products/tenant-6100-800-s10-anhui-factory-made-big-roller-sweeper-brush-dulevo-5000-main", permanent: true },
    { source: "/products/11117587233", destination: "/products/johnston-650-steel-wire-sweeper-side-brush", permanent: true },
    { source: "/products/103856773876", destination: "/products/taski-15-5inch-rider-floor-scrubber-cleaning-brush-soft-nylon-disc-scrub-brush", permanent: true },
    { source: "/products/29793555118", destination: "/products/12inch-magnet-disc-brush-for-floor-cleaning-equipment", permanent: true },
    { source: "/products/103115387387", destination: "/products/scrubber-attachment-pad-holder-driver-for-vipe-as1050r-vf82057", permanent: true },
    { source: "/products/102489750753", destination: "/products/factory-sale-nilfisk-sc3500-13inch-floor-scrubber-disc-brush-for-floor-scrubber", permanent: true },
    { source: "/products/101535642567", destination: "/products/floor-cleaning-equipment-spare-part-np-9200-aluminum-alloy-clutch-plate", permanent: true },
    { source: "/products/103423680956", destination: "/products/tenant-t300e-t500e-industrial-floor-cleaning-brush-12-inch-to-21inch-workshop-sc", permanent: true },
    { source: "/products/103774246776", destination: "/products/pad-holder-pad-driver-for-floor-machine-buffer-polisher-scrubber", permanent: true },
    { source: "/products/106910220276", destination: "/products/flexible-cylinder-silicone-carbide-flex-hone-brush-for-polishing-amp-deburring", permanent: true },
    { source: "/products/101536061230", destination: "/products/floor-scrubber-equipment-parts-175-al-alloy-clutch-plate", permanent: true },
    { source: "/products/101536037905", destination: "/products/floor-scrubber-equipment-parts-tenant-clutch-plate", permanent: true },
    { source: "/products/11120500874", destination: "/products/scarab-magnum-sweeper-steel-wire-side-brush-from-china-factory", permanent: true },
    { source: "/products/104405094338", destination: "/products/24v-3-stage-vacuum-motor-suitable-for-tenant-t7", permanent: true },
    { source: "/products/103856870150", destination: "/products/anhui-changzhong-floor-scrubber-spare-part-disc-brush-for-tennant-t12", permanent: true },
    { source: "/products/101939797515", destination: "/products/high-quality-squeegee-for-floor-scrubber-with-nr-pu-material", permanent: true },
    { source: "/products/103193590764", destination: "/products/large-commercial-city-road-cleaning-brush-efficient-street-side-sweeper-brush", permanent: true },
    { source: "/products/104568220016", destination: "/products/factory-sale-multicolor-square-bath-mat-floor-spa-shower-mat-washable-pvc-bathro", permanent: true },
    { source: "/products/103854357212", destination: "/products/professional-brush-factory-floor-scrubber-machine-brush-cleaning-supplies-china", permanent: true },
    { source: "/products/103185857178", destination: "/products/high-quality-economical-and-practical-gutter-sweeper-side-brush-for-road-sweepin", permanent: true },
    { source: "/products/103802569915", destination: "/products/cleaning-equipment-parts-rotary-brush-monobrush-with-red-buckle", permanent: true },
    { source: "/products/104411739465", destination: "/products/floor-scrubber-machine-brush-floor-buffer-pad-driver-pad-holder-for-single-disc", permanent: true },
    { source: "/products/101540180217", destination: "/products/floor-scrubber-equipment-parts-viper-clutch-plate", permanent: true },
    { source: "/products/104941150846", destination: "/products/nilfisk-viper-gaomei-machine-spare-part-carpet-shampoo-brush-carpet-washing-floo", permanent: true },
    { source: "/products/101540420408", destination: "/products/cleaning-equipment-floor-scrubber-machine-parts-invincible-clutch-plate-for-task", permanent: true },
    { source: "/products/101793279887", destination: "/products/sj50-walk-behind-compact-floor-scrubber-or-cleaning-machine-electric-motor-plast", permanent: true },
    { source: "/products/104462585771", destination: "/products/36v-24v-3-stg-vacuum-motor-tennant-viper-comac-karche-nilfisk-ipc-vacuum-cleaner", permanent: true },
    { source: "/products/101559536107", destination: "/products/floor-scrubber-spare-part-disk-brush-for-tennant-t5-t5e", permanent: true },
    { source: "/products/102016435573", destination: "/products/floor-scrubber-clutch-plate-for-kacher-tennant-nilfisk-viper-comac", permanent: true },
    { source: "/products/102013081191", destination: "/products/nilfisk-viper-as510b-20-inch-pad-driver-holder-for-floor-scrubber-vf90416", permanent: true },
    { source: "/products/102317205523", destination: "/products/single-disc-brush-carpet-brush-for-floor-scrubber-and-single-disc-machine", permanent: true },
    { source: "/products/103764246699", destination: "/products/hard-bristle-scrubbing-brush-pad-driver-pad-holder-with-short-hard-bristles-for", permanent: true },
    { source: "/products/11755941778", destination: "/products/cleaning-equipment-spare-part-15-inch-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/103708832802", destination: "/products/floor-machine-spare-parts-squeegee-assembly-squeegee-kit-floor-scrubber-squeegee", permanent: true },
    { source: "/products/101534842595", destination: "/products/cleaning-equipment-scrubber-spare-part-red-np-500-clutch-plate", permanent: true },
    { source: "/products/102005762209", destination: "/products/15-inch-floor-scrubber-pad-driver-for-viper-as380", permanent: true },
    { source: "/products/103716916645", destination: "/products/scrubber-cleaning-machine-parts-squeegee-tool-assembly", permanent: true },
    { source: "/products/103636201049", destination: "/products/china-factory-directly-sale-wholesale-tenant-t3e-drain-hose-suction-hose", permanent: true },
    { source: "/products/11703693794", destination: "/products/gaomei-auto-scrubber-machine-gm110bt85-spare-part-floor-rotary-disc-brush-pad-dr", permanent: true },
    { source: "/products/29999367172", destination: "/products/17-inch-nylon-disc-brush-for-tennant", permanent: true },
    { source: "/products/104677526589", destination: "/products/quality-wholesale-rotary-circular-industrial-floor-cleaning-brush-with-factory-p", permanent: true },
    { source: "/products/102013005760", destination: "/products/nilfisk-viper-as510b-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/103854046483", destination: "/products/high-quality-floor-scrubber-spare-part-disc-brush-for-tenant-t12", permanent: true },
    { source: "/products/102865046123", destination: "/products/factory-sales-floor-scrubber-spare-parts-for-tennant-t3-t3e-t300-t300e", permanent: true },
    { source: "/products/101940364715", destination: "/products/high-quality-floor-scrubber-squeegee-with-nr-pu-material", permanent: true },
    { source: "/products/103821455343", destination: "/products/hot-product-floor-scrubber-cleaning-machine-brush-supplies-for-tenant-karchr-vip", permanent: true },
    { source: "/products/103117233721", destination: "/products/karche-medium-nylon-brush-rotary-brush-for-floor-scrubber-components-bristle", permanent: true },
    { source: "/products/104430614171", destination: "/products/floor-scrubber-machine-roller-brush-karche-red-roller-brush-scrubber-drier", permanent: true },
    { source: "/products/103854042528", destination: "/products/high-quality-floor-scrubber-spare-part-disc-brush-for-ipc-ct40", permanent: true },
    { source: "/products/103772002824", destination: "/products/floor-buffer-single-brush-disc-rotary-stripping-brush-for-carpet-cleaning", permanent: true },
    { source: "/products/103184551546", destination: "/products/rotary-side-brush-gutter-broom-for-gasoline-cleaning-truck-road-sweeper-brushes", permanent: true },
    { source: "/products/104353959385", destination: "/products/cleaning-equipment-parts-floor-scrubber-squeegee-blades-front-and-back-rubber-fi", permanent: true },
    { source: "/products/102012701424", destination: "/products/viper-as4325-as4335-17-inch-pa-floor-scrubber-disc-brush-for-cleaning-machine", permanent: true },
    { source: "/products/104414711336", destination: "/products/floor-scrubber-machine-brush-taski-swingo-455-disc-brush-17inch-with-pp-bristle", permanent: true },
    { source: "/products/103112150590", destination: "/products/sweeper-brush-roller-brush-50-inch-polypropylene-wire-double-row-for-tennant-800", permanent: true },
    { source: "/products/102489653805", destination: "/products/factory-sale-taski-15-5inch-floor-scrubber-disc-brush-for-floor-scrubber", permanent: true },
    { source: "/products/11698632039", destination: "/products/gaomei-gm50-cleaning-equipment-part-19-inch-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/104500676903", destination: "/products/wooden-gap-cleaning-brush-hard-bristled-crevice-cleaning-brush-for-bathroom-kitc", permanent: true },
    { source: "/products/102503415461", destination: "/products/tenant-oem-1204663-hose-assy-vacuum-w-z-cuff-1-5d-31l-tenant-t300", permanent: true },
    { source: "/products/102004841157", destination: "/products/nilfisk-viper-as380-15-15-inch-pad-driver-holder-for-floor-scrubber-vf89804", permanent: true },
    { source: "/products/101558344300", destination: "/products/hako-b75r-floor-scrubber-brush-13-inch-gray-chrysanthemum-buckle-brush", permanent: true },
    { source: "/products/103851425475", destination: "/products/ice-floor-machine-brush-natural-fibre-with-nylon-bristles-cleaning-brushes", permanent: true },
    { source: "/products/103853699589", destination: "/products/factory-direct-sales-floor-scrubber-spare-part-disk-brush-for-hako-b75r-b70-b90", permanent: true },
    { source: "/products/103314100705", destination: "/products/single-disc-machine-clutch-plate-for-cleaning-machines-154-clutch-plate", permanent: true },
    { source: "/products/104567904494", destination: "/products/recycled-rubber-non-slip-foldable-floor-mat-multicolor-100-pvc-drainage-water-ba", permanent: true },
    { source: "/products/103861942931", destination: "/products/nylon-disk-scrub-brush-assembly-20inch-508mm-1210386", permanent: true },
    { source: "/products/104329347395", destination: "/products/15inch-17inch-18inch-20inch-white-black-red-floor-pad-for-single-disc-machine-fl", permanent: true },
    { source: "/products/104646805965", destination: "/products/nilfisk-advance-sc800-floor-scrubber-machine-nilfisk-56601538-squeegee-rubber", permanent: true },
    { source: "/products/102012941006", destination: "/products/nilfisk-viper-ls160-ls160hd-17-inch-floor-scrubber-carpet-brush-vf75420", permanent: true },
    { source: "/products/103196889005", destination: "/products/cleaning-equipment-parts-road-sweeper-brushes-gutter-broom-rotary-side-brush-for", permanent: true },
    { source: "/products/102013306318", destination: "/products/viper-ps480-150mm-310mm-sweeper-side-brush-vp11406", permanent: true },
    { source: "/products/100053360385", destination: "/products/hako-b45-pu-suction-rubber-for-floor-scrubber-squeegee", permanent: true },
    { source: "/products/103205871781", destination: "/products/high-quality-wholesale-customization-truck-street-sweeper-side-brush-gutter-broo", permanent: true },
    { source: "/products/101559266208", destination: "/products/cleaning-equipment-part-pp-floor-scrubber-disc-brush-for-tennant-t5e", permanent: true },
    { source: "/products/104678017449", destination: "/products/best-sale-road-cleaning-brush-floor-scrubber-brush-customized-pp-and-nylon-disc", permanent: true },
    { source: "/products/101748253843", destination: "/products/high-quality-tenant-t20-road-sweeper-roller-brush-for-floor-scrubber-in-factory", permanent: true },
    { source: "/products/102005135851", destination: "/products/nilfisk-viper-as4325-as4335-17-inch-pad-driver-holder-for-floor-scrubber-vs15440", permanent: true },
    { source: "/products/104353862224", destination: "/products/viper-auto-scrubber-solution-line-filter-vf82168a-water-filter", permanent: true },
    { source: "/products/12343985408", destination: "/products/dulevo-garant-506-floor-scubber-spare-part-abrasive-brushes", permanent: true },
    { source: "/products/102220363426", destination: "/products/17inch-ppl-factory-cat-gtx-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/105016094288", destination: "/products/tennant-370095-centering-device-pad-retainer", permanent: true },
    { source: "/products/104430484305", destination: "/products/tennant-brush-motor-aftermarket-replaces-tennant", permanent: true },
    { source: "/products/103154697251", destination: "/products/excellent-quality-custom-wholesale-floor-scrubber-machine-pad-driver", permanent: true },
    { source: "/products/103792803890", destination: "/products/scrub-brush-with-lugs-grit-brush-rotary-brush-floor-polishing", permanent: true },
    { source: "/products/104343126210", destination: "/products/china-factory-directly-sale-wholesale-replacement-clutch-plate-for-disc-brush", permanent: true },
    { source: "/products/103098210561", destination: "/products/wholesale-double-reed-price-clutch-plate-for-floor-cleaning-scrubber", permanent: true },
    { source: "/products/103737974024", destination: "/products/floor-scrubber-spare-part-blades-rubber-squeegee-scrubber-dryer-blade-cleaning-s", permanent: true },
    { source: "/products/101559806690", destination: "/products/floor-scrubber-19inch-polypropylene-disc-brush-for-tenant-t300e", permanent: true },
    { source: "/products/103128173750", destination: "/products/kacher-b140-pp-roller-brush-rotary-broom-central-brush", permanent: true },
    { source: "/products/103856659415", destination: "/products/factory-direct-sales-floor-scrubber-spare-part-disc-brush-for-viper-as430-vf9041", permanent: true },
    { source: "/products/103635651783", destination: "/products/manufacturers-flexible-braided-plastic-vacuum-hose-6mm-8mm-10mm-plastic-heater-h", permanent: true },
    { source: "/products/11674008569", destination: "/products/kacher-b90r-scrubber-spare-part-drain-hose", permanent: true },
    { source: "/products/101530132440", destination: "/products/cleaning-equipment-scrubber-spare-part-clutch-plate-np-9200", permanent: true },
    { source: "/products/103113875576", destination: "/products/pp-purpose-rotary-brushes-carpet-brush-for-floor-scrubber-machine-cleaning", permanent: true },
    { source: "/products/103131362489", destination: "/products/hard-plate-brush-rotary-stripping-brush-for-carpet-cleaning", permanent: true },
    { source: "/products/104368066424", destination: "/products/disc-brush-aftermarket-tennant-1221541-fits-tennant-a5-t5-t5e-t500-t500e", permanent: true },
    { source: "/products/104364346649", destination: "/products/floor-scrubber-spare-parts-tennant-t300e-vacuum-motor-2stage-360w", permanent: true },
    { source: "/products/101705628647", destination: "/products/comac-innova-55-spare-part-squeegee-for-floor-scrubber", permanent: true },
    { source: "/products/104365594195", destination: "/products/comac-vispa-35b-spare-part-squeegee-rubber-for-floor-scrubber-machine", permanent: true },
    { source: "/products/101704011949", destination: "/products/comac-vispa-35b-spare-part-squeegee-for-floor-scrubber", permanent: true },
    { source: "/products/104368478542", destination: "/products/tennant-222415-squeegee-blade-rubber-kits-fits-5680-5700-7200-t15-floor-scrubber", permanent: true },
    { source: "/products/101711695823", destination: "/products/taski-swingo-1250-spare-part-squeegee-for-floor-scrubber", permanent: true },
    { source: "/products/104365479773", destination: "/products/tennant-t12-compact-battery-ride-on-floor-scrubber-1220241-polypropylene-disk-sc", permanent: true },
    { source: "/products/104371798545", destination: "/products/drain-hose-tennant-t3-t5-1043538-aftermarket-parts-cleaning-supplies", permanent: true },
    { source: "/products/101705320686", destination: "/products/comac-innova-60-spare-part-squeegee-for-floor-scrubber", permanent: true },
    { source: "/products/104386244989", destination: "/products/factory-directly-sale-t3-tennant-9011849-bumper-head-bristle-skirt-retaining-str", permanent: true },
    { source: "/products/101693621322", destination: "/products/hako-b75r-cleaning-machine-part-13inch-floor-scrubber-disc-brush", permanent: true },
    { source: "/products/101650654640", destination: "/products/hako-b115r-floor-scrubber-spare-part-18-inch-scrubber-brush", permanent: true },
    { source: "/products/104371686419", destination: "/products/suction-hose-tennant-t3-t5-and-t7-1014026-fits-floor-scrubber-machine", permanent: true },
    { source: "/products/104371666361", destination: "/products/squeegee-rubber-kits-for-floor-scrubber-machine", permanent: true },
    { source: "/products/104365207500", destination: "/products/karche-kit-squeege-suction-rubber-standard-bd50-40-rs-1010-mm", permanent: true },
    { source: "/products/101711325869", destination: "/products/comac-innova-75-spare-part-squeegee-for-floor-scrubber", permanent: true },
    { source: "/products/104360096788", destination: "/products/long-service-life-relay-switch-for-floor-scrubber-machine", permanent: true },
    { source: "/products/101650838979", destination: "/products/hako-b45-floor-scrubber-spare-part-20-inch-scrubber-brush", permanent: true },
    // Old WordPress URL patterns (migration cleanup)
    { source: "/product/:slug*", destination: "/products", permanent: true },
    { source: "/product-category/:slug*", destination: "/products", permanent: true },
    { source: "/product-tag/:slug*", destination: "/products", permanent: true },
    { source: "/squeegee-assembly", destination: "/floor-scrubber-parts-quote", permanent: true },
    { source: "/aikerui-a500-floor-scrubber-dryer", destination: "/products", permanent: true },
    { source: "/home-3", destination: "/", permanent: true },
    { source: "/help-center", destination: "/faq", permanent: true },
    { source: "/resources", destination: "/guides", permanent: true },
    { source: "/customer-cabinet", destination: "/", permanent: true },
    { source: "/customer-dashboard", destination: "/", permanent: true },
    { source: "/industry", destination: "/solutions", permanent: true },
    { source: "/service", destination: "/contact", permanent: true },
    { source: "/how-bayside-eats-market-cut-cleaning-time-by-70-with-the-k500-floor-scrubber", destination: "/guides", permanent: true },
    { source: "/playstore-img", destination: "/", permanent: true },
    { source: "/placeholder-image-11", destination: "/", permanent: true },
    { source: "/tshirt6", destination: "/", permanent: true },
    { source: "/client-logo-3", destination: "/", permanent: true },
  ];
},
};

export default nextConfig;
